### PR TITLE
Use Git 2.9's new rebase/autostash functionality

### PR DESCRIPTION
**Pull request by calebthompson**
Confirm working in:

- [x] Fast-forward
- [x] No differences
- [ ] Ahead
- [ ] Diverged

Where working means:

- Completes without error
- Shows log only if getting new commits

### CODE REVIEW

**Comment by calebthompson** [comment]
This is wip

**Comment by gfontenot** [comment]
Interesting that this makes the diverged case (which I never see tbh) identical to the remote update case.

**Comment by calebthompson** [comment]
Yeah, I see it occasionally (accidental commit to master, collaborating on feature branch, etc.). I kept the separate branches because of the messaging we use, but honestly I could do without the messaging and that would simplify some of this.

**Comment by calebthompson** [comment]
The final piece of work here is that the output of `pull` includes the start and end commit, so I think we can get a speed benefit by ditching the fetch step and parsing that to get the log (now our only benefit over plain `git pull`.

**Comment by calebthompson** [comment]
Also testing that it works I guess. Wish we had a test repo.

**Comment by calebthompson** [comment]
@gfontenot check it.

**Comment by calebthompson** [comment]
This doesn't work with empty commits, as we can't specify `--keep-empty`. This leads to the behavior when there is an empty commit locally and other commits upstream that a stash occurs but the branch pointer is not moved (and the autostash is applied).

```
❯ git show-branch master origin/master
* [master] empty
 ! [origin/master] Only ever display display_{fb_,}text in UI
--
*  [master] empty
*  [master^] test
 + [origin/master] Only ever display display_{fb_,}text in UI
 + [origin/master^^2] Retry and fail OpenURI::HTTPError and EOFError
 + [origin/master^^2^] Handle RuntimeError for redirection loops and persist the original exception
 + [origin/master^^2~2] Remove unused constant
-- [master~2] Merge branch 'remove-soft-delete'

❯ git update
Created autostash: 8317550
HEAD is now at 9d09e46 empty
Applied autostash.
Nothing to do
```

**Comment by gfontenot** [comment]
@calebthompson I don't think I follow here. Is this a critical problem that's keeping us from being able to move forward on this?

**Comment by calebthompson** [comment]
Nope I've been using this and I think it works.

Caleb Thompson

Sent from
https://polymail.io/?utm_source=polymail&utm_medium=referral&utm_campaign=signature

On Mon, Sep 05, 2016 at 2:31 PM Gordon Fontenot

<
mailto:Gordon Fontenot <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/calebthompson
I don't think I follow here. Is this a critical problem that's keeping us from being able to move forward on this?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/gfontenot/git-update/pull/18#issuecomment-244802811
, or

**Pull request merged**
